{"uuid":"517f67b6-2013-4c23-85fa-1a94a57ae896","historyId":"322f67c4fe505c20d41c8fd2d01927e6","fullName":"io.cucumber.testng.AbstractTestNGCucumberTests.runScenario","labels":[{"name":"package","value":"testRunner.DsalgoRunner"},{"name":"testClass","value":"testRunner.DsalgoRunner"},{"name":"testMethod","value":"runScenario"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"testRunner.DsalgoRunner"},{"name":"host","value":"LAPTOP-2KQV9F30"},{"name":"thread","value":"25644@LAPTOP-2KQV9F30.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Runs Cucumber Scenarios","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"BUG: Expected message 'Error occurred' but got: 'Some Tests failed. Please review code'","trace":"java.lang.AssertionError: BUG: Expected message 'Error occurred' but got: 'Some Tests failed. Please review code'\r\n\tat org.junit.Assert.fail(Assert.java:89)\r\n\tat stepDefinitions.ArraysStep.the_user_gets_error_message_error_occurred_during_submission_in_the_console(ArraysStep.java:375)\r\n\tat âœ½.The user gets error message Error occurred during submission in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:123)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg1","value":"\"Arrays PracticeQuestion\""},{"name":"arg0","value":"\"Verify that user receives error on submitting invalid python code for Find Numbers with Even Number of Digits question\""}],"start":1746253048918,"stop":1746253054079}