{"uuid":"a9378959-879c-46e6-89cd-a1fddcbf8194","historyId":"1b29173687d56b7beedc975b60ea709f","fullName":"io.cucumber.testng.AbstractTestNGCucumberTests.runScenario","labels":[{"name":"package","value":"testRunner.DsalgoRunner"},{"name":"testClass","value":"testRunner.DsalgoRunner"},{"name":"testMethod","value":"runScenario"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"testRunner.DsalgoRunner"},{"name":"host","value":"LAPTOP-2KQV9F30"},{"name":"thread","value":"1132@LAPTOP-2KQV9F30.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Runs Cucumber Scenarios","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"BUG: Expected message 'Error occurred' but got: 'No tests were collected'","trace":"java.lang.AssertionError: BUG: Expected message 'Error occurred' but got: 'No tests were collected'\r\n\tat org.junit.Assert.fail(Assert.java:89)\r\n\tat stepDefinitions.ArraysStep.the_user_gets_error_message_error_occurred_during_submission_in_the_console(ArraysStep.java:375)\r\n\tat âœ½.The user gets error message Error occurred during submission in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:147)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg1","value":"\"Arrays PracticeQuestion\""},{"name":"arg0","value":"\"Verify that user receives error on submitting invalid python code for Squares of a Sorted Array question\""}],"start":1746253232679,"stop":1746253237522}