<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TCJEROD" failures="5" tests="35" name="testRunner.DsalgoRunner" time="322.565" errors="1" timestamp="2025-05-12T14:18:35 PDT" skipped="0">
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.732"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.733"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.998">
    <failure message="BUG: Expected message &#039;Error occurred&#039; but got: &#039;No tests were collected&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Error occurred' but got: 'No tests were collected' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_error_message_error_occurred_during_submission_in_the_console(ArraysStep.java:270)
at ✽.The user gets error message Error occurred during submission in the console(file:///C:/Users/Kruthi/dsAlgo2025/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:124)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.588"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="11.333"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.064"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.829"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.931">
    <failure message="BUG: Expected message &#039;Submission Successful&#039; but got: &#039;Error occurred during submission&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission Successful' but got: 'Error occurred during submission' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:289)
at ✽.The user gets success message Submission successful in the console(file:///C:/Users/Kruthi/dsAlgo2025/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:109)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.657"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="9.791"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.381"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.024"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.381">
    <failure message="BUG: Expected message &#039;Submission Successful&#039; but got: &#039;No tests were collected&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission Successful' but got: 'No tests were collected' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:289)
at ✽.The user gets success message Submission successful in the console(file:///C:/Users/Kruthi/dsAlgo2025/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:129)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.868"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.815"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.129">
    <failure message="BUG: Expected message &#039;Submission Successful&#039; but got: &#039;Some Tests failed. Please review code&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission Successful' but got: 'Some Tests failed. Please review code' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:289)
at ✽.The user gets success message Submission successful in the console(file:///C:/Users/Kruthi/dsAlgo2025/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:69)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="9.618"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="9.870"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.202"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="9.124"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.697"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.931"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="9.523"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="12.594"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="9.507"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.922"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="9.261">
    <failure message="Bug: No alert displayed when clicking Run without entering code." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Bug: No alert displayed when clicking Run without entering code.
at org.testng.Assert.fail(Assert.java:111)
at stepDefinitions.ArraysStep.the_user_should_see_an_error_message_in_alert_window(ArraysStep.java:114)
at ✽.The user should see an error message in alert window(file:///C:/Users/Kruthi/dsAlgo2025/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:22)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.437">
    <error message="stale element reference: stale element not found
  (Session info: chrome=136.0.7103.93)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: &#039;4.29.0&#039;, revision: &#039;5fc1ec94cb&#039;
System info: os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;23.0.2&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [b466e7e51625a6dad19db6bfe190eb0a, actions {actions=[org.openqa.selenium.interactions.Sequence@6a49b3c7]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.93, chrome: {chromedriverVersion: 136.0.7103.92 (cb81a4cc5087..., userDataDir: C:\Users\Kruthi\AppData\Loc...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:63544}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:63544/devtoo..., se:cdpVersion: 136.0.7103.93, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: b466e7e51625a6dad19db6bfe190eb0a" type="org.openqa.selenium.StaleElementReferenceException">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: stale element not found
  (Session info: chrome=136.0.7103.93)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.29.0', revision: '5fc1ec94cb'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [b466e7e51625a6dad19db6bfe190eb0a, actions {actions=[org.openqa.selenium.interactions.Sequence@6a49b3c7]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.93, chrome: {chromedriverVersion: 136.0.7103.92 (cb81a4cc5087..., userDataDir: C:\Users\Kruthi\AppData\Loc...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:63544}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:63544/devtoo..., se:cdpVersion: 136.0.7103.93, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: b466e7e51625a6dad19db6bfe190eb0a
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:631)
at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:616)
at org.openqa.selenium.interactions.Actions.perform(Actions.java:581)
at pageObject.ArraysPage.scrollAndClickDataStructuresDropdown(ArraysPage.java:141)
at stepDefinitions.ArraysStep.the_user_scrolls_down_to_the_data_structures_dropdown_and_selects_array(ArraysStep.java:48)
at ✽.The user scrolls down to the Data Structures dropdown and selects Array(file:///C:/Users/Kruthi/dsAlgo2025/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:5)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.974"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.343"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="9.590"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.290"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="11.054"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.968"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.406"/>
</testsuite> <!-- testRunner.DsalgoRunner -->
