<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-2KQV9F30" failures="3" tests="8" name="testRunner.DsalgoRunner" time="38.430" errors="0" timestamp="2025-05-03T01:20:42 CDT" skipped="0">
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.504"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.827"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.328"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.847">
    <failure message="BUG: Expected message &#039;Error occurred&#039; but got: &#039;No tests were collected&#039;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Error occurred' but got: 'No tests were collected'
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_gets_error_message_error_occurred_during_submission_in_the_console(ArraysStep.java:375)
at ✽.The user gets error message Error occurred during submission in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:147)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.212"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.893">
    <failure message="BUG: Expected message &#039;Submission successful&#039; but got: &#039;Error occurred during submission&#039;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission successful' but got: 'Error occurred during submission'
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:402)
at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:129)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="3.994"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.825">
    <failure message="BUG: Expected message &#039;Submission successful&#039; but got: &#039;No tests were collected&#039;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission successful' but got: 'No tests were collected'
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:402)
at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:153)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testRunner.DsalgoRunner -->
