<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-2KQV9F30" failures="8" tests="53" name="testRunner.DsalgoRunner" time="356.720" errors="0" timestamp="2025-05-12T14:29:22 CDT" skipped="0">
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.732"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.800"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="10.679"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.068"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.437"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.197"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.157"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.649">
    <failure message="BUG: Expected message &#039;Submission Successful&#039; but got: &#039;No tests were collected&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission Successful' but got: 'No tests were collected' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:146)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.480"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.143"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.541"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.791">
    <failure message="BUG: Expected message &#039;Error occurred&#039; but got: &#039;No tests were collected&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Error occurred' but got: 'No tests were collected' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_error_message_error_occurred_during_submission_in_the_console(ArraysStep.java:280)
at ✽.The user gets error message Error occurred during submission in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:140)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.378"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.787"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.250"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.496"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.353"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.951">
    <failure message="Bug: No alert displayed when clicking Run without entering code." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Bug: No alert displayed when clicking Run without entering code.
at org.testng.Assert.fail(Assert.java:111)
at stepDefinitions.StackStep.the_user_is_able_to_see_an_error_message_in_alert_window(StackStep.java:128)
at ✽.The user is able to see an error message in alert window(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Stack.feature:24)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.495"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.444"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.497">
    <failure message="BUG: Expected message &#039;Submission Successful&#039; but got: &#039;Error occurred during submission&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission Successful' but got: 'Error occurred during submission' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:122)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.928"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.413"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="4.966"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.661"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.419"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.825"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.198"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.257">
    <failure message="Bug: No alert displayed when clicking Run without entering code." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Bug: No alert displayed when clicking Run without entering code.
at org.testng.Assert.fail(Assert.java:111)
at stepDefinitions.ArraysStep.the_user_should_see_an_error_message_in_alert_window(ArraysStep.java:124)
at ✽.The user should see an error message in alert window(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:25)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.306"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.957"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.349">
    <failure message="Bug: No alert displayed when clicking Run without entering code." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Bug: No alert displayed when clicking Run without entering code.
at org.testng.Assert.fail(Assert.java:111)
at stepDefinitions.StackStep.the_user_is_able_to_see_an_error_message_in_alert_window(StackStep.java:128)
at ✽.The user is able to see an error message in alert window(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Stack.feature:55)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.861"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.686"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.432"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.697"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.908"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.036"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.852"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.679"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="7.093"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.795"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.216"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.416"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.631"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="8.354">
    <failure message="Bug: No alert displayed when clicking Run without entering code." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Bug: No alert displayed when clicking Run without entering code.
at org.testng.Assert.fail(Assert.java:111)
at stepDefinitions.StackStep.the_user_is_able_to_see_an_error_message_in_alert_window(StackStep.java:128)
at ✽.The user is able to see an error message in alert window(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Stack.feature:86)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.050"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.002"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.734">
    <failure message="BUG: Expected message &#039;Submission Successful&#039; but got: &#039;Some Tests failed. Please review code&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: BUG: Expected message 'Submission Successful' but got: 'Some Tests failed. Please review code' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.ArraysStep.the_user_gets_success_message_submission_successful_in_the_console(ArraysStep.java:299)
at ✽.The user gets success message Submission successful in the console(file:///C:/Workspace/Ds-Algo2025/src/test/resources/Feature/Arrays.feature:75)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="5.256"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.557"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.475"/>
  <testcase classname="testRunner.DsalgoRunner" name="runScenario" time="6.386"/>
</testsuite> <!-- testRunner.DsalgoRunner -->
